### ISSUE TITLE
Is there Any setting so In my local load css, js and fonts etc from my local and on live server load from CDN?

### ISSUE THREAD

**Issue by jayeshcspl** [arubacao/asset-cdn#10]
Really plugin is very awesome.

I need small help from you.

Can we do that so when I run site from my local system it loads all css, js and fonts from my local so when internet is not working then I can also work easily. And  when I run live site all things load from CDN.

Is there any settting for that?

Thank you for your great help and support.

**Comment by arubacao** [comment]
For this, use the environment variable `USE_CDN`. `true` on your live site, `false` locally

**Comment by jayeshcspl** [comment]
Thank you very much.
It's working fine.
