### ISSUE TITLE
asset_cdn with id= (cache busting)

### ISSUE THREAD

**Issue by patricksebastien** [arubacao/asset-cdn#11]
There's something I'm not understanding, when using:
`{{ style(mix_cdn('css/frontend.css')) }}` the result is `<link media="all" type="text/css" rel="stylesheet" href="https://cdn.agora.community/css/frontend.css?id=e0496e6f8f90bb488b9e">` :+1: 

How to use versionning for asset_cdn? Trying to `<img src="{{ asset_cdn("test.png") }}">` the result is `<img src="https://mycdn.com/test.png">` no ?id= append.

So now updating an image on S3 is not updated on the website. Trying to bust the 1 year cache configured on the object meta-data on S3.

**Comment by arubacao** [comment]
Is `test.png` versioned in `mix-manifest.json` ?

**Comment by patricksebastien** [comment]
That's the part I was not understanding. Thanks, so in the end I moved my images from public/img to resources/assets/img and included a copy + version in webpack.mix.js:

```
const mix = require('laravel-mix');

// hack to version image
// https://github.com/JeffreyWay/laravel-mix/issues/1193
mix.copyOutsideMixWorkflow = function (from, to) {
    new File(from).copyTo(new File(to).path());

    return this;
}.bind(mix);
...
.copyOutsideMixWorkflow('resources/assets/', 'public')
.mix.version(["public/img"])
```

Thank you!

**Comment by arubacao** [comment]
Yes, that's the easiest way to go.
My suggestion: Add a folder `resources/assets/public` for everything you need versioned under public
