### ISSUE TITLE
inlcude files problem

### ISSUE THREAD

**Issue by mkosmen** [arubacao/asset-cdn#6]
finder search files use regexp but i need only full path. for example if i write

```
'include' => [
    'paths' => [
         'js',
         'css',
     ]
]
```

finder should find files in only public/js and public/css folders but it finds files in all js and css folder in public folder. it is a bug think and i need help ...

**Comment by arubacao** [comment]
This is not a bug. If you need "public/js" and "pulic/css" then you have to be specific in the config file.
Your example is described in detail here: 
https://github.com/arubacao/asset-cdn#4-edit-files-in-configasset-cdnphp

**Comment by mkosmen** [comment]
yes this is a bug i think cus you write that : 

> **"any other 'js' or 'css'"**

> but also any other 'js' or 'css' path e.g.
> '/var/www/html/public/vendor/js'
> '/var/www/html/public/vendor/css'
> You could explicitly exclude paths later

i dont want exclude paths ... if i write public/js and dont want to get vendor/js files i must exclude it, right ? please fix it ...

**Comment by arubacao** [comment]
This library utilizes ["Finder" from Symfony](https://github.com/symfony/finder)
If you think this is a bug, you should submit your issue there.
You just need to be more explicit with your configuration.

**Comment by mkosmen** [comment]
this is my config and as it seems i must add exclude paths all sub uploads folder

```php
'asset' => [
    'files' => [
        'ignoreVCS' => false,
        'include' => [
            'paths' => [
                'uploads',
            ]
        ],
        'exclude' => [
            'paths' => [
                'assets/uploads',
                '_uploads',
                'user/uploads',
                'admin/uploads',
                'cache/uploads'
            ]
        ]
    ]
]
```

I think it must be like below :

```php
'asset' => [
    'push' => [
        'paths' => [
            'uploads'
        ],
        'files' => [],
        'match' => [],
    ],
    // we can use if we need some exclude path or files
    'exclude' => [
        'paths' => [],
        'files' => [],
        'match' => [],
    ]
]
```
