### ISSUE TITLE
Laravel 7 support?

### ISSUE THREAD

**Issue by heyaj19** [arubacao/asset-cdn#7]
Laravel 7 came out - I was wondering if there will be any support for it ?

**Comment by arubacao** [comment]
Hey @heyaj19 
There will be Laravel 7 support, I just haven't had the time yet. If you have the capacity, feel free to submit a PR.

**Comment by arubacao** [comment]
Enjoy https://github.com/arubacao/asset-cdn/releases/tag/0.2.3 !
